// ─────────────────────────────────────────────────────────────
// Export Utilities — CSV + Print-to-PDF
// ─────────────────────────────────────────────────────────────

/**
 * Convert an array of objects to a CSV string and trigger download.
 * @param rows   - array of plain objects (all values stringified)
 * @param filename - without extension
 * @param headers  - optional custom column header labels
 */
export function exportCSV(
  rows: Record<string, unknown>[],
  filename: string,
  headers?: Record<string, string>
): void {
  if (!rows.length) return;

  const keys = Object.keys(rows[0]);

  // Header row
  const headerRow = keys
    .map(k => `"${(headers?.[k] || k).replace(/"/g, '""')}"`)
    .join(',');

  // Data rows
  const dataRows = rows.map(row =>
    keys.map(k => {
      const val = row[k] ?? '';
      const str = String(val).replace(/"/g, '""');
      return `"${str}"`;
    }).join(',')
  );

  const csv = [headerRow, ...dataRows].join('\r\n');
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' }); // BOM for Excel
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `${filename}_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Open a print dialog with the provided HTML string.
 * Browser prints it — user chooses "Save as PDF" in the dialog.
 */
export function exportPrintPDF(
  html: string,
  title: string
): void {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>${title}</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; color: #111; padding: 24px; }
          h1  { font-size: 20px; font-weight: 700; margin-bottom: 4px; }
          h2  { font-size: 14px; font-weight: 600; margin: 16px 0 6px; color: #555; }
          p.sub { font-size: 11px; color: #888; margin-bottom: 16px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
          th { background: #f3f4f6; font-weight: 600; text-align: left; padding: 7px 10px; border-bottom: 2px solid #e5e7eb; font-size: 11px; }
          td { padding: 6px 10px; border-bottom: 1px solid #f3f4f6; font-size: 11px; }
          tr:last-child td { border-bottom: none; }
          .kpi { display: inline-block; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 20px; margin: 0 8px 12px 0; }
          .kpi-val { font-size: 22px; font-weight: 700; }
          .kpi-lbl { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 0.05em; }
          .footer { margin-top: 24px; font-size: 10px; color: #aaa; border-top: 1px solid #eee; padding-top: 8px; }
          @media print { @page { margin: 16mm; } }
        </style>
      </head>
      <body>
        ${html}
        <div class="footer">Generated by ZAINA Salon Management · ${new Date().toLocaleString()}</div>
      </body>
    </html>
  `);
  win.document.close();
  setTimeout(() => { win.focus(); win.print(); }, 400);
}

// ── Convenience builders ──────────────────────────────────────

/** Build a simple HTML table from rows */
export function buildHTMLTable(
  rows: Record<string, unknown>[],
  headers: Record<string, string>,
  title: string,
  subtitle?: string
): string {
  const keys = Object.keys(headers);
  const headerHTML = keys.map(k => `<th>${headers[k]}</th>`).join('');
  const rowsHTML = rows.map(r =>
    `<tr>${keys.map(k => `<td>${r[k] ?? ''}</td>`).join('')}</tr>`
  ).join('');

  return `
    <h1>${title}</h1>
    ${subtitle ? `<p class="sub">${subtitle}</p>` : ''}
    <table>
      <thead><tr>${headerHTML}</tr></thead>
      <tbody>${rowsHTML}</tbody>
    </table>
  `;
}

/** Build KPI summary block */
export function buildKPIBlock(kpis: { label: string; value: string | number }[]): string {
  return kpis.map(k => `
    <div class="kpi">
      <div class="kpi-val">${k.value}</div>
      <div class="kpi-lbl">${k.label}</div>
    </div>
  `).join('');
}
