import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';

/**
 * Atomic-ish GRN stock + WAC update with optimistic concurrency.
 *
 * Previous code read (current_stock, cost_price) then wrote back computed
 * values — races under any concurrent sale or GRN clobber data.  Same
 * pattern as the B.8 fix in useTransactions.ts but for the receive
 * direction (stock up, WAC blended).
 *
 * Returns success + new values so the audit row can log them accurately.
 */
interface GRNApplyResult {
  ok: boolean;
  newStock?: number;
  newWAC?: number;
}

async function safeApplyGRN(
  productId: string,
  receivedQty: number,
  receivedCost: number,
  MAX_RETRIES = 4,
): Promise<GRNApplyResult> {
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const { data: product, error } = await supabase
      .from('products')
      .select('current_stock, cost_price')
      .eq('id', productId)
      .single();
    if (error || !product) return { ok: false };

    const oldStock = Number(product.current_stock || 0);
    const oldCost  = Number(product.cost_price || 0);
    const newStock = oldStock + receivedQty;
    // WAC — weighted-average cost: (existing value + received value) / total qty
    const newWAC = newStock > 0
      ? ((oldStock * oldCost) + (receivedQty * receivedCost)) / newStock
      : receivedCost;
    const roundedWAC = Math.round(newWAC * 1000) / 1000;

    const { error: updErr, count } = await supabase
      .from('products')
      .update({
        current_stock: newStock,
        cost_price:    roundedWAC,
      } as any)
      .eq('id', productId)
      .eq('current_stock', oldStock) // optimistic guard
      .select('*');

    if (!updErr && (count ?? 1) > 0) {
      return { ok: true, newStock, newWAC: roundedWAC };
    }
    // lost the race — loop and retry
  }
  return { ok: false };
}

export interface GoodsReceipt {
  id: string;
  grn_number: string;
  purchase_order_id: string;
  tenant_id: string;
  received_by: string | null;
  notes: string | null;
  received_at: string;
  purchase_order?: {
    id: string;
    po_number: string;
    supplier_id: string;
    status: string;
    supplier?: {
      id: string;
      name: string;
      name_ar: string | null;
    };
  };
}

export interface GoodsReceiptItem {
  id: string;
  goods_receipt_id: string;
  product_id: string;
  po_item_id: string | null;
  quantity_received: number;
  unit_cost: number;
  batch_number: string | null;
  expiry_date: string | null;
  product?: {
    id: string;
    name: string;
    name_ar: string | null;
    sku: string | null;
    current_stock: number;
    cost_price: number;
  };
}

export const useGoodsReceipts = () => {
  const { tenant } = useAuth();
  return useQuery({
    queryKey: ['goods_receipts', tenant?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('goods_receipts')
        .select('*, purchase_order:purchase_orders(id, po_number, supplier_id, status, supplier:suppliers(id, name, name_ar))')
        .order('received_at', { ascending: false });
      if (error) throw error;
      return data as unknown as GoodsReceipt[];
    },
    enabled: !!tenant?.id,
  });
};

export const useGoodsReceiptItems = (grId: string | null) => {
  return useQuery({
    queryKey: ['goods_receipt_items', grId],
    queryFn: async () => {
      if (!grId) return [];
      const { data, error } = await supabase
        .from('goods_receipt_items')
        .select('*, product:products(id, name, name_ar, sku, current_stock, cost_price)')
        .eq('goods_receipt_id', grId);
      if (error) throw error;
      return data as unknown as GoodsReceiptItem[];
    },
    enabled: !!grId,
  });
};

/**
 * WAC formula:
 * New WAC = (Existing Stock * Current WAC + Received Qty * Received Unit Cost) / (Existing Stock + Received Qty)
 */
export const useCreateGoodsReceipt = () => {
  const queryClient = useQueryClient();
  const { tenant, user } = useAuth();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: {
      purchase_order_id: string;
      notes?: string;
      items: {
        product_id: string;
        po_item_id: string;
        quantity_received: number;
        unit_cost: number;
        batch_number?: string;
        expiry_date?: string;
      }[];
    }) => {
      // 1. Create GR header (grn_number auto-generated by trigger)
      const { data: gr, error: grError } = await supabase
        .from('goods_receipts')
        .insert({
          purchase_order_id: data.purchase_order_id,
          tenant_id: tenant!.id,
          received_by: user?.id || null,
          notes: data.notes || null,
          grn_number: 'TEMP', // overwritten by trigger
        })
        .select()
        .single();
      if (grError) throw grError;

      // 2. Insert GR items
      const grItems = data.items.map(item => ({
        goods_receipt_id: gr.id,
        product_id: item.product_id,
        po_item_id: item.po_item_id,
        quantity_received: item.quantity_received,
        unit_cost: item.unit_cost,
        batch_number: item.batch_number || null,
        expiry_date: item.expiry_date || null,
      }));
      const { error: itemsError } = await supabase
        .from('goods_receipt_items')
        .insert(grItems);
      if (itemsError) throw itemsError;

      // Collected warnings surfaced to the clerk after the GRN closes.
      const grnWarnings: string[] = [];

      // 3. For each item: atomic stock+WAC update + inventory transaction + PO item qty update
      for (const item of data.items) {
        // 3a. Apply stock + WAC atomically with retries.
        const applied = await safeApplyGRN(
          item.product_id,
          item.quantity_received,
          item.unit_cost,
        );

        if (!applied.ok) {
          grnWarnings.push(
            `Stock update failed for product ${item.product_id} — inventory may be out of sync. Manager review needed.`
          );
          // Still record the intent in the audit log so the failure is traceable.
          await supabase
            .from('inventory_transactions')
            .insert({
              tenant_id: tenant!.id,
              product_id: item.product_id,
              transaction_type: 'purchase_receipt' as any,
              quantity_change: item.quantity_received,
              reference_type: 'goods_receipt',
              reference_id: gr.id,
              notes: `GRN but stock update failed — needs reconciliation. Unit cost: ${item.unit_cost}`,
              created_by: user?.id || null,
            } as any);
        } else {
          await supabase
            .from('inventory_transactions')
            .insert({
              tenant_id: tenant!.id,
              product_id: item.product_id,
              transaction_type: 'purchase_receipt' as any,
              quantity_change: item.quantity_received,
              reference_type: 'goods_receipt',
              reference_id: gr.id,
              notes: `GR against PO. Unit cost: ${item.unit_cost}, New WAC: ${applied.newWAC!.toFixed(3)}`,
              created_by: user?.id || null,
            } as any);
        }

        // 3b. Update PO item quantity_received.  Warn on over-receive —
        //     accept it (salons sometimes get extra or wrong quantities
        //     in the box), but flag so the buyer knows to call the
        //     supplier or reconcile.
        if (item.po_item_id) {
          const { data: poItem } = await supabase
            .from('purchase_order_items')
            .select('quantity_ordered, quantity_received, product_id')
            .eq('id', item.po_item_id)
            .single();
          if (poItem) {
            const newReceived = (poItem.quantity_received || 0) + item.quantity_received;
            if (poItem.quantity_ordered && newReceived > poItem.quantity_ordered) {
              const over = newReceived - poItem.quantity_ordered;
              grnWarnings.push(
                `Over-receive: line exceeds PO by ${over}. Verify packing slip vs PO.`
              );
            }
            await supabase
              .from('purchase_order_items')
              .update({ quantity_received: newReceived })
              .eq('id', item.po_item_id);
          }
        }
      }

      // 4. Check if PO is fully or partially received
      const { data: allPoItems } = await supabase
        .from('purchase_order_items')
        .select('quantity_ordered, quantity_received')
        .eq('po_id', data.purchase_order_id);

      if (allPoItems) {
        const allReceived = allPoItems.every(i => i.quantity_received >= i.quantity_ordered);
        const someReceived = allPoItems.some(i => i.quantity_received > 0);
        const newStatus = allReceived ? 'received' : someReceived ? 'partially_received' : undefined;
        if (newStatus) {
          await supabase
            .from('purchase_orders')
            .update({ status: newStatus } as any)
            .eq('id', data.purchase_order_id);
        }
      }

      // Attach warnings so onSuccess can surface them.
      (gr as any).__grnWarnings = grnWarnings;
      return gr;
    },
    onSuccess: (gr: any) => {
      queryClient.invalidateQueries({ queryKey: ['goods_receipts'] });
      queryClient.invalidateQueries({ queryKey: ['purchase_orders'] });
      queryClient.invalidateQueries({ queryKey: ['purchase_order_items'] });
      queryClient.invalidateQueries({ queryKey: ['products'] });
      queryClient.invalidateQueries({ queryKey: ['inventory_transactions'] });
      toast({ title: 'Goods received & stock updated with WAC recalculation' });

      const warnings: string[] = gr?.__grnWarnings || [];
      if (warnings.length) {
        toast({
          title: 'GRN warnings',
          description: warnings.slice(0, 3).join('\n') + (warnings.length > 3 ? `\n…and ${warnings.length - 3} more` : ''),
          variant: 'destructive',
        });
      }
    },
    onError: (error) => {
      toast({ title: 'Failed to receive goods', description: error.message, variant: 'destructive' });
    },
  });
};
