import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';

export interface GoodsReceipt {
  id: string;
  grn_number: string;
  purchase_order_id: string;
  tenant_id: string;
  received_by: string | null;
  notes: string | null;
  received_at: string;
  purchase_order?: {
    id: string;
    po_number: string;
    supplier_id: string;
    status: string;
    supplier?: {
      id: string;
      name: string;
      name_ar: string | null;
    };
  };
}

export interface GoodsReceiptItem {
  id: string;
  goods_receipt_id: string;
  product_id: string;
  po_item_id: string | null;
  quantity_received: number;
  unit_cost: number;
  batch_number: string | null;
  expiry_date: string | null;
  product?: {
    id: string;
    name: string;
    name_ar: string | null;
    sku: string | null;
    current_stock: number;
    cost_price: number;
  };
}

export const useGoodsReceipts = () => {
  const { tenant } = useAuth();
  return useQuery({
    queryKey: ['goods_receipts', tenant?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('goods_receipts')
        .select('*, purchase_order:purchase_orders(id, po_number, supplier_id, status, supplier:suppliers(id, name, name_ar))')
        .order('received_at', { ascending: false });
      if (error) throw error;
      return data as unknown as GoodsReceipt[];
    },
    enabled: !!tenant?.id,
  });
};

export const useGoodsReceiptItems = (grId: string | null) => {
  return useQuery({
    queryKey: ['goods_receipt_items', grId],
    queryFn: async () => {
      if (!grId) return [];
      const { data, error } = await supabase
        .from('goods_receipt_items')
        .select('*, product:products(id, name, name_ar, sku, current_stock, cost_price)')
        .eq('goods_receipt_id', grId);
      if (error) throw error;
      return data as unknown as GoodsReceiptItem[];
    },
    enabled: !!grId,
  });
};

/**
 * WAC formula:
 * New WAC = (Existing Stock * Current WAC + Received Qty * Received Unit Cost) / (Existing Stock + Received Qty)
 */
export const useCreateGoodsReceipt = () => {
  const queryClient = useQueryClient();
  const { tenant, user } = useAuth();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: {
      purchase_order_id: string;
      notes?: string;
      items: {
        product_id: string;
        po_item_id: string;
        quantity_received: number;
        unit_cost: number;
        batch_number?: string;
        expiry_date?: string;
      }[];
    }) => {
      // 1. Create GR header (grn_number auto-generated by trigger)
      const { data: gr, error: grError } = await supabase
        .from('goods_receipts')
        .insert({
          purchase_order_id: data.purchase_order_id,
          tenant_id: tenant!.id,
          received_by: user?.id || null,
          notes: data.notes || null,
          grn_number: 'TEMP', // overwritten by trigger
        })
        .select()
        .single();
      if (grError) throw grError;

      // 2. Insert GR items
      const grItems = data.items.map(item => ({
        goods_receipt_id: gr.id,
        product_id: item.product_id,
        po_item_id: item.po_item_id,
        quantity_received: item.quantity_received,
        unit_cost: item.unit_cost,
        batch_number: item.batch_number || null,
        expiry_date: item.expiry_date || null,
      }));
      const { error: itemsError } = await supabase
        .from('goods_receipt_items')
        .insert(grItems);
      if (itemsError) throw itemsError;

      // 3. For each item: WAC recalculation + stock update + inventory transaction + PO item qty update
      for (const item of data.items) {
        // Fetch current product data
        const { data: product } = await supabase
          .from('products')
          .select('current_stock, cost_price')
          .eq('id', item.product_id)
          .single();

        if (product) {
          const existingStock = product.current_stock || 0;
          const existingCost = product.cost_price || 0;
          const receivedQty = item.quantity_received;
          const receivedCost = item.unit_cost;

          // WAC calculation
          const totalStock = existingStock + receivedQty;
          const newWAC = totalStock > 0
            ? ((existingStock * existingCost) + (receivedQty * receivedCost)) / totalStock
            : receivedCost;

          // Update product stock and cost
          await supabase
            .from('products')
            .update({
              current_stock: totalStock,
              cost_price: Math.round(newWAC * 1000) / 1000, // 3 decimal precision
            } as any)
            .eq('id', item.product_id);

          // Log inventory transaction
          await supabase
            .from('inventory_transactions')
            .insert({
              tenant_id: tenant!.id,
              product_id: item.product_id,
              transaction_type: 'purchase_receipt' as any,
              quantity_change: receivedQty,
              reference_type: 'goods_receipt',
              reference_id: gr.id,
              notes: `GR against PO. Unit cost: ${receivedCost}, New WAC: ${newWAC.toFixed(3)}`,
              created_by: user?.id || null,
            } as any);
        }

        // Update PO item quantity_received
        if (item.po_item_id) {
          const { data: poItem } = await supabase
            .from('purchase_order_items')
            .select('quantity_received')
            .eq('id', item.po_item_id)
            .single();
          if (poItem) {
            await supabase
              .from('purchase_order_items')
              .update({ quantity_received: (poItem.quantity_received || 0) + item.quantity_received })
              .eq('id', item.po_item_id);
          }
        }
      }

      // 4. Check if PO is fully or partially received
      const { data: allPoItems } = await supabase
        .from('purchase_order_items')
        .select('quantity_ordered, quantity_received')
        .eq('po_id', data.purchase_order_id);

      if (allPoItems) {
        const allReceived = allPoItems.every(i => i.quantity_received >= i.quantity_ordered);
        const someReceived = allPoItems.some(i => i.quantity_received > 0);
        const newStatus = allReceived ? 'received' : someReceived ? 'partially_received' : undefined;
        if (newStatus) {
          await supabase
            .from('purchase_orders')
            .update({ status: newStatus } as any)
            .eq('id', data.purchase_order_id);
        }
      }

      return gr;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['goods_receipts'] });
      queryClient.invalidateQueries({ queryKey: ['purchase_orders'] });
      queryClient.invalidateQueries({ queryKey: ['purchase_order_items'] });
      queryClient.invalidateQueries({ queryKey: ['products'] });
      queryClient.invalidateQueries({ queryKey: ['inventory_transactions'] });
      toast({ title: 'Goods received & stock updated with WAC recalculation' });
    },
    onError: (error) => {
      toast({ title: 'Failed to receive goods', description: error.message, variant: 'destructive' });
    },
  });
};
