import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import type { Database } from '@/integrations/supabase/types';

type POStatus = Database['public']['Enums']['po_status'];
type POSentVia = Database['public']['Enums']['po_sent_via'];

export interface PurchaseOrder {
  id: string;
  tenant_id: string;
  supplier_id: string;
  po_number: string;
  status: POStatus;
  total_amount: number;
  notes: string | null;
  payment_terms: string | null;
  requested_by: string | null;
  approved_by: string | null;
  approved_at: string | null;
  sent_via: POSentVia | null;
  sent_at: string | null;
  created_at: string;
  updated_at: string;
  supplier?: {
    id: string;
    name: string;
    name_ar: string | null;
    email: string | null;
    whatsapp_number: string | null;
  };
}

export interface PurchaseOrderItem {
  id: string;
  po_id: string;
  product_id: string;
  quantity_ordered: number;
  quantity_received: number;
  unit_cost: number;
  total_cost: number;
  product?: {
    id: string;
    name: string;
    name_ar: string | null;
    sku: string | null;
    usage_unit: string | null;
  };
}

export const PO_STATUS_CONFIG: Record<POStatus, { label: string; color: string }> = {
  draft: { label: 'Draft', color: 'bg-muted text-muted-foreground' },
  pending_approval: { label: 'Pending Approval', color: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' },
  approved: { label: 'Approved', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200' },
  sent: { label: 'Sent', color: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200' },
  partially_received: { label: 'Partially Received', color: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200' },
  received: { label: 'Received', color: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' },
  cancelled: { label: 'Cancelled', color: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' },
};

export const usePurchaseOrders = (statusFilter?: string) => {
  const { tenant } = useAuth();

  return useQuery({
    queryKey: ['purchase_orders', tenant?.id, statusFilter],
    queryFn: async () => {
      let query = supabase
        .from('purchase_orders')
        .select('*, supplier:suppliers(id, name, name_ar, email, whatsapp_number)')
        .order('created_at', { ascending: false });

      if (statusFilter && statusFilter !== 'all') {
        query = query.eq('status', statusFilter as POStatus);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as unknown as PurchaseOrder[];
    },
    enabled: !!tenant?.id,
  });
};

export const usePurchaseOrderItems = (poId: string | null) => {
  return useQuery({
    queryKey: ['purchase_order_items', poId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('purchase_order_items')
        .select('*, product:products(id, name, name_ar, sku, usage_unit)')
        .eq('po_id', poId!)
        .order('id');

      if (error) throw error;
      return data as unknown as PurchaseOrderItem[];
    },
    enabled: !!poId,
  });
};

export const useCreatePurchaseOrder = () => {
  const queryClient = useQueryClient();
  const { tenant, user } = useAuth();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: {
      supplier_id: string;
      notes?: string;
      payment_terms?: string;
      items: { product_id: string; quantity_ordered: number; unit_cost: number }[];
    }) => {
      const totalAmount = data.items.reduce((sum, i) => sum + i.quantity_ordered * i.unit_cost, 0);

      // Create PO - po_number is auto-generated by trigger
      const { data: po, error: poError } = await supabase
        .from('purchase_orders')
        .insert({
          tenant_id: tenant?.id!,
          supplier_id: data.supplier_id,
          notes: data.notes || null,
          payment_terms: data.payment_terms || null,
          total_amount: totalAmount,
          requested_by: user?.id || null,
          status: 'draft' as POStatus,
          po_number: 'TEMP', // Will be overwritten by trigger
        })
        .select()
        .single();

      if (poError) throw poError;

      // Create line items
      const items = data.items.map((item) => ({
        po_id: po.id,
        product_id: item.product_id,
        quantity_ordered: item.quantity_ordered,
        unit_cost: item.unit_cost,
        total_cost: item.quantity_ordered * item.unit_cost,
      }));

      const { error: itemsError } = await supabase
        .from('purchase_order_items')
        .insert(items);

      if (itemsError) throw itemsError;

      return po;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['purchase_orders'] });
      toast({ title: 'Purchase Order created successfully' });
    },
    onError: (error) => {
      toast({ title: 'Failed to create PO', description: error.message, variant: 'destructive' });
    },
  });
};

export const useUpdatePOStatus = () => {
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, status, notes }: { id: string; status: POStatus; notes?: string }) => {
      const updateData: Record<string, unknown> = { status };

      if (status === 'approved') {
        updateData.approved_by = user?.id;
        updateData.approved_at = new Date().toISOString();
      }

      if (status === 'sent') {
        updateData.sent_at = new Date().toISOString();
        updateData.sent_via = 'manual' as POSentVia;
      }

      if (notes !== undefined) {
        updateData.notes = notes;
      }

      const { data, error } = await supabase
        .from('purchase_orders')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['purchase_orders'] });
      queryClient.invalidateQueries({ queryKey: ['purchase_order_items'] });
      const statusLabel = PO_STATUS_CONFIG[variables.status]?.label || variables.status;
      toast({ title: `PO status updated to ${statusLabel}` });
    },
    onError: (error) => {
      toast({ title: 'Failed to update PO status', description: error.message, variant: 'destructive' });
    },
  });
};
